"""added is2FA is true as defualt

Revision ID: a86b949aa1cc
Revises: c727ea464dd9
Create Date: 2024-11-30 15:54:28.415796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86b949aa1cc'
down_revision: Union[str, None] = 'c727ea464dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
